### ISSUE TITLE
Incorrect Axis Markings

### ISSUE THREAD

**Issue by jrleeman** [sparkfun/MAG3110_Breakout_Board#6]
The markings for the axes on the breakout are incorrect. The y-axis is fine, but the x is mirrored on the bottom and the z is marked "up" on both the top and bottom. From my reading of the data sheet, the z points down, so it should be marked with x in a circle on top, and the dot in a circle on bottom. The x direction marked on the top of the board is correct. 

![bottom](https://cloud.githubusercontent.com/assets/325269/9552442/1acd2844-4d86-11e5-8c65-5ffa61109a51.jpg)
![top](https://cloud.githubusercontent.com/assets/325269/9552443/1ad3ec74-4d86-11e5-9855-b99bdc29faf2.jpg)
![from_datasheet](https://cloud.githubusercontent.com/assets/325269/9552449/22df514c-4d86-11e5-9a3b-0baeddb7ea33.png)

**Comment by bboyho** [comment]
Hi,

Thanks for filing the issue. I confirmed the issue that you are seeing and you are correct. Unfortunately, the chip is EOL and was retired from the SparkFun catalog. Therefore, we are not able to revise the silkscreen. I'll be closing out this issue.
